version: '3.8'

services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command:
      - npm
      - run
      - start
