version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command:
      - npm
      - run
      - start:dev
