version: '3.8'

services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    command:
      - npm
      - run
      - start
