version: '3.8'

services:
  node-app:
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=node-app
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data

volumes:
  mongo-db:
  redis-db:

